INSIDER_RISK_POLICIES = [
    {
        "policy_id": "ir-departing-001",
        "name": "Data Theft by Departing Users",
        "description": "Detects data exfiltration activities by employees who have submitted resignation or been flagged for termination.",
        "template": "Data theft by departing users",
        "triggers": ["HR resignation event", "Termination notification from HR connector"],
        "risk_indicators": [
            "Downloading large volumes of files",
            "Copying files to USB/removable storage",
            "Emailing files to personal email",
            "Uploading to personal cloud storage",
            "Accessing unusual file shares",
        ],
        "priority_content": ["Source code", "Customer data", "Financial records", "Intellectual property"],
        "timeframe": "30 days before last day",
        "severity": "High",
        "tags": ["departing", "termination", "resignation", "data-theft"],
    },
    {
        "policy_id": "ir-leaks-001",
        "name": "General Data Leaks",
        "description": "Monitors for general data exfiltration patterns across all users without specific trigger events.",
        "template": "General data leaks",
        "triggers": ["Always on - no trigger required"],
        "risk_indicators": [
            "Unusual volume of file downloads",
            "Multiple failed access attempts",
            "Access to sensitive content outside business hours",
            "Sharing to unverified external domains",
        ],
        "priority_content": ["Confidential documents", "Customer PII", "Financial data"],
        "timeframe": "Continuous monitoring",
        "severity": "Medium",
        "tags": ["data-leak", "exfiltration", "general", "monitoring"],
    },
    {
        "policy_id": "ir-priority-001",
        "name": "Priority User Data Leaks",
        "description": "Enhanced monitoring for high-risk users such as executives, IT admins, and users with privileged access.",
        "template": "Data leaks by priority users",
        "triggers": ["Priority user group membership"],
        "risk_indicators": [
            "All file download activities",
            "External sharing of any sensitive content",
            "Cloud service uploads",
            "Email forwarding patterns",
        ],
        "priority_content": ["All sensitive content types"],
        "timeframe": "Continuous monitoring",
        "severity": "High",
        "tags": ["priority-user", "executive", "privileged", "data-leak"],
    },
    {
        "policy_id": "ir-disgruntled-001",
        "name": "Disgruntled Employee Security Policy Violations",
        "description": "Identifies security violations and policy bypasses by employees showing disgruntled behavior patterns.",
        "template": "Security policy violations by departing users",
        "triggers": ["HR performance improvement plan", "Disciplinary action event"],
        "risk_indicators": [
            "Attempting to disable security software",
            "Accessing colleagues accounts",
            "Deleting large amounts of data",
            "Visiting job search sites extensively",
            "Aggressive email communications",
        ],
        "priority_content": ["Security tools", "HR systems", "Financial systems"],
        "timeframe": "Duration of HR action period",
        "severity": "High",
        "tags": ["disgruntled", "security-violation", "policy-bypass"],
    },
    {
        "policy_id": "ir-patient-001",
        "name": "Patient Data Misuse (Healthcare)",
        "description": "Detects inappropriate access or sharing of patient health records by healthcare workers.",
        "template": "Patient data misuse",
        "triggers": ["Always on"],
        "risk_indicators": [
            "Accessing patient records outside care team",
            "Bulk download of patient records",
            "Sharing PHI to personal devices",
            "Printing patient records in bulk",
        ],
        "priority_content": ["Patient records", "PHI", "EHR data"],
        "timeframe": "Continuous",
        "severity": "High",
        "tags": ["healthcare", "hipaa", "patient", "phi", "misuse"],
    },
    {
        "policy_id": "ir-browser-001",
        "name": "Risky Browser Usage",
        "description": "Monitors risky browser activities including accessing dark web, hacking forums, or malware distribution sites.",
        "template": "Risky browser usage",
        "triggers": ["Always on"],
        "risk_indicators": [
            "Accessing dark web domains",
            "Visiting known malware distribution sites",
            "Browsing hacking or exploit forums",
            "Accessing cryptocurrency exchanges from work",
            "Using anonymization proxies",
        ],
        "priority_content": ["Browser history indicators"],
        "timeframe": "Continuous",
        "severity": "Medium",
        "tags": ["browser", "web", "dark-web", "risky", "malware"],
    },
    {
        "policy_id": "ir-cumulative-001",
        "name": "Cumulative Exfiltration Detection",
        "description": "Detects slow, low-volume data exfiltration that might evade single-event thresholds.",
        "template": "Data leaks",
        "triggers": ["Always on - cumulative scoring"],
        "risk_indicators": [
            "Steady daily file downloads over extended period",
            "Gradual increase in external sharing",
            "Regular small uploads to cloud services",
            "Consistent after-hours access patterns",
        ],
        "priority_content": ["All content types"],
        "timeframe": "Rolling 30-day window",
        "severity": "Medium",
        "tags": ["cumulative", "slow-leak", "exfiltration", "pattern"],
    },
]
