RETENTION_POLICIES = [
    {
        "policy_id": "ret-hipaa-001",
        "name": "HIPAA Medical Records Retention",
        "description": "Retain medical records for minimum 6 years per HIPAA requirements",
        "retention_period": {"value": 6, "unit": "years"},
        "applies_to": ["Medical Records", "PHI", "Treatment Records"],
        "regulatory_basis": "HIPAA 45 CFR 164.530(j)",
        "disposition": "Review before delete",
        "locations": ["SharePoint", "OneDrive", "Exchange"],
    },
    {
        "policy_id": "ret-sox-001",
        "name": "SOX Financial Records Retention",
        "description": "Retain financial records for 7 years per Sarbanes-Oxley requirements",
        "retention_period": {"value": 7, "unit": "years"},
        "applies_to": ["Financial Statements", "Audit Records", "Accounting Data"],
        "regulatory_basis": "SOX Section 802",
        "disposition": "Delete after review",
        "locations": ["Exchange", "SharePoint", "OneDrive"],
    },
    {
        "policy_id": "ret-gdpr-001",
        "name": "GDPR Data Minimization Retention",
        "description": "Minimize personal data retention per GDPR storage limitation principle",
        "retention_period": {"value": 3, "unit": "years"},
        "applies_to": ["EU Personal Data", "Customer Records", "Marketing Data"],
        "regulatory_basis": "GDPR Article 5(1)(e)",
        "disposition": "Auto-delete",
        "locations": ["Exchange", "SharePoint", "OneDrive", "Teams"],
    },
    {
        "policy_id": "ret-legal-001",
        "name": "Legal Hold Retention",
        "description": "Preserve all content relevant to litigation or regulatory inquiry",
        "retention_period": {"value": 10, "unit": "years"},
        "applies_to": ["Legal Documents", "Contracts", "Litigation Materials"],
        "regulatory_basis": "FRCP Rule 26",
        "disposition": "Manual review required",
        "locations": ["Exchange", "SharePoint", "OneDrive", "Teams"],
    },
    {
        "policy_id": "ret-email-001",
        "name": "General Email Retention",
        "description": "Standard email retention policy for business communications",
        "retention_period": {"value": 3, "unit": "years"},
        "applies_to": ["Business Email", "Calendar Items"],
        "regulatory_basis": "Business best practice",
        "disposition": "Auto-delete",
        "locations": ["Exchange"],
    },
    {
        "policy_id": "ret-pci-001",
        "name": "PCI DSS Cardholder Data Retention",
        "description": "Limit cardholder data retention to minimum necessary per PCI DSS",
        "retention_period": {"value": 1, "unit": "years"},
        "applies_to": ["Credit Card Data", "Payment Records"],
        "regulatory_basis": "PCI DSS Requirement 3.1",
        "disposition": "Secure delete",
        "locations": ["SharePoint", "OneDrive"],
    },
    {
        "policy_id": "ret-hr-001",
        "name": "HR Employee Records Retention",
        "description": "Retain employee records for 7 years after termination",
        "retention_period": {"value": 7, "unit": "years"},
        "applies_to": ["Employee Records", "Performance Reviews", "Compensation Data"],
        "regulatory_basis": "FLSA, EEOC regulations",
        "disposition": "Review before delete",
        "locations": ["SharePoint", "Exchange"],
    },
    {
        "policy_id": "ret-contract-001",
        "name": "Contract Retention Policy",
        "description": "Retain contracts for 7 years after expiration",
        "retention_period": {"value": 7, "unit": "years"},
        "applies_to": ["Contracts", "Agreements", "SLAs", "NDAs"],
        "regulatory_basis": "UCC, common law",
        "disposition": "Legal review before delete",
        "locations": ["SharePoint", "OneDrive"],
    },
    {
        "policy_id": "ret-tax-001",
        "name": "Tax Records Retention",
        "description": "Retain tax records for minimum 7 years per IRS requirements",
        "retention_period": {"value": 7, "unit": "years"},
        "applies_to": ["Tax Returns", "W-2", "1099", "Expense Reports"],
        "regulatory_basis": "IRS Publication 583",
        "disposition": "Review before delete",
        "locations": ["Exchange", "SharePoint"],
    },
    {
        "policy_id": "ret-ccpa-001",
        "name": "CCPA California Consumer Data Retention",
        "description": "Limit California consumer personal data retention per CCPA",
        "retention_period": {"value": 2, "unit": "years"},
        "applies_to": ["California Consumer Data", "Marketing Data", "Purchase History"],
        "regulatory_basis": "CCPA Section 1798.100",
        "disposition": "Auto-delete with notification",
        "locations": ["Exchange", "SharePoint", "OneDrive"],
    },
]
