SENSITIVE_INFO_TYPES = [
    {
        "name": "Credit Card Number",
        "id": "50842eb7-edc8-4019-85dd-5a5c1f2bb085",
        "description": "Detects credit card numbers from major card networks including Visa, Mastercard, AmEx, Discover",
        "category": "Financial",
        "patterns": [r"\b4[0-9]{12}(?:[0-9]{3})?\b", r"\b5[1-5][0-9]{14}\b"],
        "keywords": ["credit card", "card number", "cvv", "expiry", "expire", "visa", "mastercard"],
        "confidence_level": "High",
        "example_values": ["4111 1111 1111 1111", "5500 0000 0000 0004"],
    },
    {
        "name": "U.S. Social Security Number (SSN)",
        "id": "a44669fe-0d48-453d-a9b1-2cc83f2cba77",
        "description": "Detects US Social Security Numbers in formatted and unformatted patterns",
        "category": "Government IDs",
        "patterns": [r"\b\d{3}-\d{2}-\d{4}\b", r"\b\d{9}\b"],
        "keywords": ["SSN", "social security", "social security number"],
        "confidence_level": "High",
        "example_values": ["123-45-6789"],
    },
    {
        "name": "U.S. Passport Number",
        "id": "e3cb0d13-0ef8-4f3c-af5e-5f5b8f6b31b2",
        "description": "Detects US passport numbers in standard 9-digit format",
        "category": "Government IDs",
        "patterns": [r"\b[A-Z]{1}\d{8}\b"],
        "keywords": ["passport", "travel document", "US passport"],
        "confidence_level": "Medium",
        "example_values": ["A12345678"],
    },
    {
        "name": "U.S. Driver's License Number",
        "id": "dfeb116e-a598-4513-a465-e6ac8b7f8e5a",
        "description": "Detects US driver's license numbers (patterns vary by state)",
        "category": "Government IDs",
        "patterns": [r"\b[A-Z]{1,2}\d{5,8}\b"],
        "keywords": ["driver's license", "driving license", "DL number", "state ID"],
        "confidence_level": "Medium",
        "example_values": ["D12345678"],
    },
    {
        "name": "International Bank Account Number (IBAN)",
        "id": "bcd9bbf6-6f09-4462-b4c4-73e5bc82a89e",
        "description": "Detects IBAN numbers for international bank transfers",
        "category": "Financial",
        "patterns": [r"\b[A-Z]{2}\d{2}[A-Z0-9]{11,30}\b"],
        "keywords": ["IBAN", "international bank account", "bank transfer"],
        "confidence_level": "High",
        "example_values": ["GB29 NWBK 6016 1331 9268 19"],
    },
    {
        "name": "SWIFT Code",
        "id": "c1ef62c5-4c61-4fce-9bbc-fd0ab2b03c3b",
        "description": "Detects SWIFT/BIC codes used for international wire transfers",
        "category": "Financial",
        "patterns": [r"\b[A-Z]{6}[A-Z0-9]{2}(?:[A-Z0-9]{3})?\b"],
        "keywords": ["SWIFT", "BIC", "bank code", "wire transfer"],
        "confidence_level": "Medium",
        "example_values": ["NWBKGB2L", "CHASUS33"],
    },
    {
        "name": "EU National Identification Number",
        "id": "419f449a-f6bb-4a7e-a1e3-a51af7b8d60e",
        "description": "Detects national ID numbers for EU member states",
        "category": "Government IDs",
        "patterns": [r"\b\d{9,12}\b"],
        "keywords": ["national ID", "EU ID", "personal ID", "identification number"],
        "confidence_level": "Medium",
        "example_values": ["123456789"],
    },
    {
        "name": "EU Passport Number",
        "id": "8b5e3b8b-c982-4b2e-82a3-1f32e5c7b948",
        "description": "Detects EU member state passport numbers",
        "category": "Government IDs",
        "patterns": [r"\b[A-Z]{2}\d{7}\b"],
        "keywords": ["EU passport", "European passport", "passport number"],
        "confidence_level": "Medium",
        "example_values": ["DE1234567"],
    },
    {
        "name": "UK National Insurance Number",
        "id": "6a2f56bb-c3d0-4c78-b61f-5f5b8f7d3a1a",
        "description": "Detects UK National Insurance numbers",
        "category": "Government IDs",
        "patterns": [r"\b[A-Z]{2}\d{6}[A-D]\b"],
        "keywords": ["NI number", "national insurance", "NINO", "UK NI"],
        "confidence_level": "High",
        "example_values": ["AB123456C"],
    },
    {
        "name": "Canadian Social Insurance Number",
        "id": "9f9a5c7e-d2a8-4d5b-b934-6e9c1f2d3b4a",
        "description": "Detects Canadian Social Insurance Numbers (SIN)",
        "category": "Government IDs",
        "patterns": [r"\b\d{3}[- ]\d{3}[- ]\d{3}\b"],
        "keywords": ["SIN", "social insurance number", "Canadian SIN"],
        "confidence_level": "High",
        "example_values": ["123 456 789"],
    },
    {
        "name": "Australian Tax File Number",
        "id": "a2c3d4e5-f6g7-h8i9-j0k1-l2m3n4o5p6q7",
        "description": "Detects Australian Tax File Numbers (TFN)",
        "category": "Financial",
        "patterns": [r"\b\d{8,9}\b"],
        "keywords": ["TFN", "tax file number", "Australian tax"],
        "confidence_level": "Medium",
        "example_values": ["123 456 789"],
    },
    {
        "name": "U.S. Bank Account Number",
        "id": "b3c4d5e6-f7a8-b9c0-d1e2-f3g4h5i6j7k8",
        "description": "Detects US bank account numbers typically 8-17 digits",
        "category": "Financial",
        "patterns": [r"\b\d{8,17}\b"],
        "keywords": ["bank account", "account number", "checking account", "savings account"],
        "confidence_level": "Medium",
        "example_values": ["12345678901"],
    },
    {
        "name": "ABA Routing Number",
        "id": "c4d5e6f7-a8b9-c0d1-e2f3-g4h5i6j7k8l9",
        "description": "Detects US ABA bank routing numbers (9 digits)",
        "category": "Financial",
        "patterns": [r"\b\d{9}\b"],
        "keywords": ["routing number", "ABA", "bank routing", "ACH routing"],
        "confidence_level": "Low",
        "example_values": ["021000021"],
    },
    {
        "name": "U.S. Medical Terms Dictionary",
        "id": "d5e6f7a8-b9c0-d1e2-f3a4-b5c6d7e8f9a0",
        "description": "Detects medical terminology suggesting PHI in documents",
        "category": "Healthcare",
        "patterns": [r"\b(diagnosis|prognosis|prescription|treatment|medication|patient|clinical)\b"],
        "keywords": ["diagnosis", "prognosis", "treatment", "medication", "patient", "clinical"],
        "confidence_level": "Low",
        "example_values": ["diagnosis of hypertension", "prescribed medication"],
    },
    {
        "name": "International Classification of Diseases (ICD)",
        "id": "e6f7a8b9-c0d1-e2f3-a4b5-c6d7e8f9a0b1",
        "description": "Detects ICD-9 and ICD-10 diagnostic codes used in medical records",
        "category": "Healthcare",
        "patterns": [r"\b[A-Z]\d{2}(?:\.\d{1,4})?\b", r"\b\d{3}(?:\.\d{1,2})?\b"],
        "keywords": ["ICD-10", "ICD-9", "diagnosis code", "medical code"],
        "confidence_level": "Medium",
        "example_values": ["E11.9", "250.00"],
    },
    {
        "name": "Drug Enforcement Agency (DEA) Number",
        "id": "f7a8b9c0-d1e2-f3a4-b5c6-d7e8f9a0b1c2",
        "description": "Detects DEA registration numbers assigned to medical practitioners",
        "category": "Healthcare",
        "patterns": [r"\b[A-Z]{2}\d{7}\b"],
        "keywords": ["DEA number", "DEA registration", "controlled substance"],
        "confidence_level": "High",
        "example_values": ["AB1234563"],
    },
    {
        "name": "Drug Names Dictionary",
        "id": "a8b9c0d1-e2f3-a4b5-c6d7-e8f9a0b1c2d3",
        "description": "Detects prescription and over-the-counter drug names suggesting PHI context",
        "category": "Healthcare",
        "patterns": [r"\b(metformin|lisinopril|atorvastatin|amoxicillin|levothyroxine)\b"],
        "keywords": ["prescription drug", "medication", "Rx", "pharmaceutical"],
        "confidence_level": "Low",
        "example_values": ["prescribed metformin 500mg"],
    },
    {
        "name": "HIV Test Result",
        "id": "b9c0d1e2-f3a4-b5c6-d7e8-f9a0b1c2d3e4",
        "description": "Detects HIV test results and related clinical data",
        "category": "Healthcare",
        "patterns": [r"\b(HIV|AIDS|CD4|antiretroviral|viral load)\b"],
        "keywords": ["HIV", "AIDS", "antiretroviral", "viral load", "CD4"],
        "confidence_level": "High",
        "example_values": ["HIV positive", "CD4 count 450"],
    },
    {
        "name": "Mental Health Terms",
        "id": "c0d1e2f3-a4b5-c6d7-e8f9-a0b1c2d3e4f5",
        "description": "Detects mental health terminology suggesting sensitive clinical PHI",
        "category": "Healthcare",
        "patterns": [r"\b(depression|anxiety|bipolar|schizophrenia|PTSD|psychiatry)\b"],
        "keywords": ["mental health", "psychiatric", "behavioral health", "counseling", "therapy"],
        "confidence_level": "Low",
        "example_values": ["diagnosed with depression", "psychiatric evaluation"],
    },
    {
        "name": "Medicare Beneficiary Number",
        "id": "d1e2f3a4-b5c6-d7e8-f9a0-b1c2d3e4f5a6",
        "description": "Detects Medicare Beneficiary Identifier (MBI) numbers",
        "category": "Healthcare",
        "patterns": [r"\b[1-9][A-Z][A-Z0-9]\d[A-Z][A-Z0-9]\d[A-Z]{2}\d{2}\b"],
        "keywords": ["Medicare", "MBI", "Medicare number", "beneficiary"],
        "confidence_level": "High",
        "example_values": ["1EG4-TE5-MK72"],
    },
    {
        "name": "Email Address",
        "id": "e2f3a4b5-c6d7-e8f9-a0b1-c2d3e4f5a6b7",
        "description": "Detects email addresses (PII when combined with other identifiers)",
        "category": "PII",
        "patterns": [r"\b[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}\b"],
        "keywords": ["email", "e-mail", "@"],
        "confidence_level": "Low",
        "example_values": ["user@example.com"],
    },
    {
        "name": "Phone Number",
        "id": "f3a4b5c6-d7e8-f9a0-b1c2-d3e4f5a6b7c8",
        "description": "Detects US and international phone numbers",
        "category": "PII",
        "patterns": [r"\b(?:\+1\s?)?\(?\d{3}\)?[\s.\-]\d{3}[\s.\-]\d{4}\b"],
        "keywords": ["phone", "telephone", "mobile", "cell phone"],
        "confidence_level": "Low",
        "example_values": ["+1 (555) 123-4567"],
    },
    {
        "name": "IP Address",
        "id": "a4b5c6d7-e8f9-a0b1-c2d3-e4f5a6b7c8d9",
        "description": "Detects IPv4 and IPv6 addresses (may indicate network documentation)",
        "category": "Technical",
        "patterns": [r"\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b"],
        "keywords": ["IP address", "IPv4", "IPv6", "network address"],
        "confidence_level": "Low",
        "example_values": ["192.168.1.1", "10.0.0.1"],
    },
    {
        "name": "Azure Storage Account Key",
        "id": "b5c6d7e8-f9a0-b1c2-d3e4-f5a6b7c8d9e0",
        "description": "Detects Azure Storage Account access keys (base64 encoded 88-char strings)",
        "category": "Cloud Credentials",
        "patterns": [r"[a-zA-Z0-9+/]{88}=="],
        "keywords": ["Azure storage key", "storage account key", "AccountKey"],
        "confidence_level": "High",
        "example_values": ["DefaultEndpointsProtocol=https;AccountName=...;AccountKey=..."],
    },
    {
        "name": "AWS Access Key ID",
        "id": "c6d7e8f9-a0b1-c2d3-e4f5-a6b7c8d9e0f1",
        "description": "Detects AWS access key IDs used for programmatic AWS access",
        "category": "Cloud Credentials",
        "patterns": [r"\b(AKIA|ASIA|AROA)[A-Z0-9]{16}\b"],
        "keywords": ["AWS access key", "AWS_ACCESS_KEY_ID", "IAM key"],
        "confidence_level": "High",
        "example_values": ["AKIAIOSFODNN7EXAMPLE"],
    },
    {
        "name": "Generic Password",
        "id": "d7e8f9a0-b1c2-d3e4-f5a6-b7c8d9e0f1a2",
        "description": "Detects potential passwords in documents based on context keywords",
        "category": "Credentials",
        "patterns": [r"(?i)(password|passwd|pwd)\s*[:=]\s*\S+"],
        "keywords": ["password", "passwd", "credential", "secret"],
        "confidence_level": "Medium",
        "example_values": ["password=MyP@ssw0rd"],
    },
    {
        "name": "Source Code Indicators",
        "id": "e8f9a0b1-c2d3-e4f5-a6b7-c8d9e0f1a2b3",
        "description": "Detects source code patterns suggesting code files being shared",
        "category": "Intellectual Property",
        "patterns": [r"\b(function|class|import|def|public|private|void)\b"],
        "keywords": ["source code", "function", "class", "import", "repository"],
        "confidence_level": "Low",
        "example_values": ["public class MyClass {", "def calculate():"],
    },
    {
        "name": "Employee ID",
        "id": "f9a0b1c2-d3e4-f5a6-b7c8-d9e0f1a2b3c4",
        "description": "Detects employee identification numbers",
        "category": "HR",
        "patterns": [r"\b(?:EMP|EID|EMPID)[A-Z0-9]{4,10}\b"],
        "keywords": ["employee ID", "EMP ID", "badge number", "personnel number"],
        "confidence_level": "Medium",
        "example_values": ["EMP123456"],
    },
    {
        "name": "Salary Information",
        "id": "a0b1c2d3-e4f5-a6b7-c8d9-e0f1a2b3c4d5",
        "description": "Detects salary and compensation information in documents",
        "category": "HR",
        "patterns": [r"(?i)\$\d{2,3}(?:,\d{3})*(?:\.\d{2})?"],
        "keywords": ["salary", "compensation", "annual pay", "base salary", "wage"],
        "confidence_level": "Low",
        "example_values": ["$75,000", "annual salary of $95,000"],
    },
    {
        "name": "Legal Terms and Case Numbers",
        "id": "b1c2d3e4-f5a6-b7c8-d9e0-f1a2b3c4d5e6",
        "description": "Detects legal case numbers and privileged document indicators",
        "category": "Legal",
        "patterns": [r"\b(?:Case|Docket|Civil)\s+No\.?\s*\d+[-:]\d+\b"],
        "keywords": ["attorney-client", "privileged", "litigation", "case number", "legal hold"],
        "confidence_level": "Medium",
        "example_values": ["Case No. 2023-CV-12345"],
    },
]
